### ISSUE TITLE
Unable to load DLL 'SNESAPU'

### ISSUE THREAD

**Issue by SirNectarine** [VitorVilela7/SPCtoMML#1]
I'm a complete noob to C#, and I want to try to get this tool working. I used msbuild on the solution file and the process went through, but now whenever I try to load an SPC, it dives me the error "Can't load SPC file: Unable to load DLL 'SNESAPU': The specified module could not be found. (Exception from HRESULT: 0x8007007E)". Please help!

**Comment by VitorVilela7** [comment]
Copy the included SNESAPU.DLL file from the release zip: [https://github.com/VitorVilela7/SPCtoMML/releases/download/V1000/SPCtoMML.zip](https://github.com/VitorVilela7/SPCtoMML/releases/download/V1000/SPCtoMML.zip) on your output folder and it might work.

**Comment by SirNectarine** [comment]
Also a noob to github, and didn't realize there was a 'releases' tab. Thank you.
I'm still glad to have Visual Studio though, lol.
